### ISSUE TITLE
Picture not showing

### ISSUE THREAD

**Issue by inconis** [W3Layouts/gatsby-starter-delog#4]
Hi,
After installation i upload with gh-pages on my github page [inconis.github.io/blog](https://inconis.github.io/blog) but unlike running on my pc picture are not avaible.
Can you help fixing this ?
Thanks

The problem might be in the fact that image source is `/assets/image-5.jpg` instad of `/blog/assets/image-5.jpg`
I have also added this script `"deploy": "gatsby build --prefix-paths && gh-pages -d public",` in `package.json` and `pathPrefix: "/blog",` in `gatsby-config.js`

**Comment by munwr** [comment]
Hi @inconis,
As you mentioned this the problem of the wrong path of the image. you can change the same in markdown file of the particular post at `thumbnail` to output proper path.

**Comment by inconis** [comment]
Yes and No ahah. If you check my empty blog I changed on the firs post but when i prepare the website with lacal server I can't see any picture (if i change the path) so i need to upload every time the blog online.
There is a way to fix this and see preview as the published version ?
Thanks

**Comment by munwr** [comment]
The published version is deployed in netlify, the path handling is done via Netlify CMS. 

if want you can hard code the path here https://github.com/W3Layouts/gatsby-starter-delog/blob/109b93b42385238da52cf46e8e80d8a77730e42d/src/components/post-link.js#L8

hope this fixes the issue

**Comment by inconis** [comment]
Hi @munwr thanks for your answer.
My Blog is deployed on github, 
How i can edit this line to include the pathPrefix only when deployed but not locally?
Sorry but i'havent studeid js.
Thanks !

**Comment by munwr** [comment]
> How i can edit this line to include the pathPrefix only when deployed but not locally?
that takes up lot of logic. like getting development and production variable the appending the string. Try https://stackoverflow.com/questions/tagged/delog am sure you will get help here :)

**Comment by inconis** [comment]
Thanks !
